version: '3.9'
services:
  frontend:
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile
    hostname: node-frontend
    ports:
        - 3000:3000
    env_file:
      - .env
    networks:
      - homework-network

networks:
  homework-network:
    name: homework-network
