apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    app: {{ include "backend.name" . }}
spec:
  replicas: {{ .Values.backendImage.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.name" . }}
    spec:
      containers:
        - name: {{ include "backend.name" . }}
          image: "{{ .Values.backendImage.repository }}:{{ .Values.backendImage.tag }}"
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backendImage.containerPort }}
          env:
            - name: REDIS_ENDPOINT
              value: "{{ .Release.Name }}-redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: DB_ENDPOINT
              value: "{{ .Release.Name }}-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "{{ .Values.postgresql.auth.database }}"
            - name: DB_USER
              value: "{{ .Values.postgresql.auth.username }}"
            - name: DB_PASS
              value: "{{ .Values.postgresql.auth.password }}"
            - name: REDIS_SKIP_VERIFY
              value: "false"
