build:
	@echo "Building it-works-on-my-machine..."
	docker-compose up --build
up:
	@echo "Up it-works-on-my-machine..."
	docker-compose up -d

down:
	@echo "Down it-works-on-my-machine..."
	docker-compose down
up-monitoring:
	@echo "Up it-works-on-my-machine monitoring..."
	docker-compose -f docker-compose-monitoring.yml up --build
