build:
	@echo "Building it-works-on-my-machine..."
	docker-compose up --build
up:
	@echo "Up it-works-on-my-machine..."
	docker-compose up -d

down:
	@echo "Down it-works-on-my-machine..."
	docker-compose down
