global:
  scrape_interval:      15s
  evaluation_interval:  15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - homework-alertmanager:9093

scrape_configs:
  - job_name: myapp
    scrape_interval: 10s
    static_configs:
      - targets: [ 'backend:8080' ]

  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]
